[package]
name = "interval-check"
version = "0.1.0"
edition = "2024"

[dependencies]
notify-rust = "4.10"
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1.36", features = ["rt", "macros", "io-util", "process", "sync"] }

[profile.release]
lto = "fat"
strip = true
